blogapp/urls.py
from django.urls import path
from . import views


app_name = 'blogapp'

urlpatterns = [
    path('post_list', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('profile', views.userprofile, name='userprofile'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    
] 

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('login/', include('loginapp.urls', 'loginapp')),
    path('posts/', include('blogapp.urls', 'blogapp')),
    path('admin/', admin.site.urls),

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

loginapp/urls.py
from django.urls import path
from . import views

app_name='loginapp'

urlpatterns =[
    path('', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('signup', views.signup, name='signup'),
    path('password_reset', views.password_reset, name='password_reset')
]

blogapp/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User



# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    image = models.ImageField(upload_to='media/img', blank=True, null=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

loginapp/models.py
from django.db import models

# Create your models here.

blogapp/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model=Post
        fields = {'title','image', 'text',}

blogapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Post
from .forms import PostForm
from django.contrib.auth.decorators import login_required
from .models import *


# Create your views here.
@login_required
def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    return render(request, 'blogapp/index.html', {'posts': posts})

@login_required
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blogapp/post_detail.html', {'post': post})

@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blogapp:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blogapp/post_edit.html', {'form': form})

@login_required
def userprofile(request):
    user_posts=Post.objects.filter(user=request.user).order_by('-published_date')
    context = {'user_posts': user_posts}
    return render(request, 'blogapp/profile.html', context)

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES or None, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blogapp/post_edit.html', {'form': form})

loginapp/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from .utils import random_string



def login(request):
        context = {}
        if request.method =="POST":
                user = authenticate(request, username=request.POST['user'], password=request.POST['password'])
                if user:
                        dj_login(request, user)
                        return HttpResponseRedirect(reverse('blogapp:post_list'))
                else:
                        context = {'error': 'Username or password is wrong.'}

        return render(request, 'loginapp/login.html', context)


def logout(request):
        dj_logout(request)
        return HttpResponseRedirect(reverse('loginapp:login'))

def signup(request):
        if User.is_authenticated:
                dj_logout(request)
        context = {}
        if request.method =='POST':
                if not request.POST['password'] == request.POST['repeat-password']:
                        context['error'] ='Passwords do not match'
                        return render(request, 'loginapp/signup.html', context)
                if len(User.objects.filter(username=request.POST['user'])) > 0:
                        context['error'] = 'Username already exists.'
                        return render(request, 'loginapp/signup.html', context)
                user = User.objects.create_user(request.POST['user'], password=request.POST['password'])

                user.save()
                dj_login(request, user)
                return HttpResponseRedirect(reverse('blogapp:post_list'))
        return render(request, 'loginapp/signup.html')

def password_reset(request):
    context = {}
    if request.method == 'POST':
        new_password = random_string()
        users =User.objects.filter(username=request.POST['user'])
        if users:
            user = users[0]
            new_password = random_string()
            user.set_password(new_password)
            user.save()
            print(f'**** User {user} change password to {new_password}')
            return HttpResponseRedirect(reverse('loginapp:login'))
        else:
            context['error'] ='NO such user!!!!!!!!!!!! not correct'
    return render(request, 'loginapp/password_reset.html')

blogapp/templates/blogapp/base.html
{% load static %}

<head>
    <title>Edita's blog</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css" />
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/blog.css' %}" />
</head>

<body>
    <div class="page-header">
        <h1><a href="{% url 'blogapp:post_list' %}">Blog</a></h1>
        <div class="top-menu-rigth">
            {% if user.is_authenticated %}
            <a href="{% url 'blogapp:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a> {% endif %}
            <a href="{% url 'blogapp:userprofile' %}" class="top-menu">
                <h2>Profile</h2>
            </a>
            <a href="{% url 'loginapp:logout' %}" class="top-menu">
                <h2>Log out</h2>
            </a>
        </div>
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                {% block content %} 
                {% endblock %}
            </div>
        </div>
    </div>
</body>

blogapp/templates/blogapp/index.html
{% extends "blogapp/base.html" %} 
{% load static %}

{% block content %}
    {% for post in posts %}
         <div class="post">
          <div class="date">
            {{ post.published_date }}
            </div>
             <h2>
            <a href="{% url 'blogapp:post_detail' pk=post.pk %}">{{ post.title }}</a>
            </h2>
                   
            {% if post.image %}
            <img src="{{ post.image.url }}" alt="img" height="300" width="400"> 
            {% endif %}
            <p>{{ post.text | linebreaksbr }}</p>
        </div>
    {% endfor %} 
{% endblock %}
        

blogapp/templates/blogapp/password_reset.html
{% extends "blogapp/base.html" %} 
{% load static %}

 {% block content %}

{% endblock %}

  <h1>Password reset</h1>
    
    <form action="{% url 'loginapp:password_reset'%}" method="POST">
        {% csrf_token %}
        <label for="user">Username</label>
        </br>
        <input type="text" name="user" id="user" placeholder="User name">
        </br>

        <input type="submit" value="Submit">
    </form>
    {% if error %}
    <p class="error">{{ error }}</p>
    {% endif %}

blogapp/templates/blogapp/post_detail.html
{% extends "blogapp/base.html" %} 
{% block content %}
<div class="post">
    {% if post.published_date %}
    <div class="date">

        {{ post.published_date }}
    </div>
    {% endif %} {% if post.user == user %}
    <a class="btn btn-default" href="{% url 'blogapp:post_edit' pk=post.pk %}"><span
            class="glyphicon glyphicon-pencil"></span></a> {% endif %}
    <h2>{{ post.title }}</h2>
     {% if post.image %}
            <img src="{{ post.image.url }}" alt="img" height="300" width="400"> 
            {% endif %}
    <p>{{ post.text|linebreaksbr }}</p>
</div>
{% endblock %}

blogapp/templates/blogapp/post_edit.html
{% extends 'blogapp/base.html' %} {% block content%}
<h2>New post</h2>
<form method="POST" class="post-form" enctype='multipart/form-data'>
    {% csrf_token %} {{ form.as_p}}
    <button type="submit" class="save btn btn-default"> Save </button>
</form>
{% endblock%}

blogapp/templates/blogapp/profile.html
 {% extends "blogapp/base.html" %} 
 {% load static %}

                {% block content %} {% for post in user_posts %}
                <div class="post">
                    <div class="date">
                        {{ post.published_date }}
                    </div>
                    <h2>
                        <a href="{% url 'blogapp:post_detail' pk=post.pk %}">{{ post.title }}</a>
                    </h2>
                    {% if post.image %}
                    <img src="{{ post.image.url }}" alt="img" height="300" width="400"> {% endif %}
                    <p>{{ post.text | linebreaksbr }}</p>
                </div>
                {% endfor %} {% endblock %}
        

loginapp/templates/loginapp/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css" />
    <link rel="stylesheet" href="{% static 'css/blog.css' %}" />
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css" />
    <title>Login</title>
</head>

<body>
    <div class="page-header">
        <h1>Blog</h1>

    </div>
    <div class="centered-form">
        <h1>Login</h1>

 
        <form action="." method="POST">
            {% csrf_token %}
            <label for="user">
                <h4>Username</h4>
            </label>
            </br>
            <input type="text" name="user" id="user" placeholder="User name">
            </br>
            <label for="password">
                <h4>Password</h4>
            </label>
            </br>
            <input type="password" name="password" id="password" placeholder="Password">
            </br>
            <input type="submit" value="Submit">
        </form>
        {% if error %}
        <p class="error">{{ error }}</p>
        <p> <a href="{% url 'loginapp:password_reset' %}">Reset password? </a></p>
        {% endif %}
        <a href="{% url 'loginapp:signup' %}">Dont have a user?</a>
    </div>
</body>

</html>

loginapp/templates/loginapp/password_reset.html
 <h1>Password reset</h1>
    
    <form action="{% url 'loginapp:password_reset'%}" method="POST">
        {% csrf_token %}
        <label for="user">Username</label>
        </br>
        <input type="text" name="user" id="user" placeholder="User name">
        </br>

        <input type="submit" value="Submit">
    </form>
    {% if error %}
    <p class="error">{{ error }}</p>
    {% endif %}

loginapp/templates/loginapp/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css" />
    <link rel="stylesheet" href="{% static 'css/blog.css' %}" />
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css" />
    <title>Sign up</title>
</head>

<body>
        <div class="page-header">
        <h1>Blog</h1> 
        </div>
        <div class="centered-form">
    <h1>Signup</h1>

    <form action="{% url 'loginapp:signup' %}" method="post">
        {% csrf_token%}
        <label for="user">Username</label>
        </br>
        <input type="text" name="user" id="user" placeholder="User name">
        </br>
        <label for="password">Password</label>
        </br>
        <input type="password" name="password" id="password" placeholder="Password">
        </br>
        <label for="repeat-password">Password</label>
        </br>
        <input type="password" name="repeat-password" id="reapeat-password" placeholder="Repeat password">
        </br>
        <input type="submit" value="Submit">

    </form>
</div>
</body>

</html>